export const SET_CLIENTE = 'SET_CLIENTE';
export const HANDLE_CLOSE = 'HANDLE_CLOSE';

export const SET_MODULO = 'SET_MODULO';
export const SET_ANSWER = 'SET_ANSWER';
export const RESET_ANSWER = 'RESET_ANSWER';
export const SET_IMAGE = 'SET_IMAGE';
export const RESET_IMAGE = 'RESET_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const RESPONSE = 'RESPONSE';
export const RESET_RESPONSE = 'RESET_RESPONSE';
export const QUESTION_LIST = 'QUESTION_LIST';
export const SET_RESPONSE_ITEM = 'SET_RESPONSE_ITEM';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_CARGA = 'SET_CARGA';
export const SET_FILTER_RESPONSE = 'SET_FILTER_RESPONSE';
export const RESET_FILTER_RESPONSE = 'RESET_FILTER_RESPONSE';